booking/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('library.urls')),
]

library/urls.py
from django.urls import path
from .views import home, profile, BookLoginView, BookLogoutView, ChangeUserInfoView, BookChangePasswordView, \
    RegisterUserView, RegisterDone, BookDeleteView, CreateArticle

app_name = 'library'

urlpatterns = [
    path('', home, name='home'),
    path('accounts/login/', BookLoginView.as_view(), name='login'),
    path('accounts/logout/', BookLogoutView.as_view(), name='logout'),
    path('accounts/profile/', profile, name='profile'),
    path('accounts/profile/change/', ChangeUserInfoView.as_view(), name='change_info'),
    path('accounts/password/change/', BookChangePasswordView.as_view(), name='change_password'),
    path('accounts/register/done/', RegisterDone.as_view(), name='register_done'),
    path('accounts/register/', RegisterUserView.as_view(), name='register_user'),
    path('account/profile/delete/', BookDeleteView.as_view(), name='delete_user'),
    path('create-article/', CreateArticle.as_view(), name='create_article'),
    path('article/', ListArticle.as_view(), name='list_article'),
]

library/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class AdvUser(AbstractUser):
    is_activated = models.BooleanField(default=True, db_index=True, verbose_name="Прошел активацию?")
    send_message = models.BooleanField(default=True, verbose_name="Слать сообщения о новых книгах?")

    class Meta(AbstractUser.Meta):
        pass


class Article(models.Model):
    title = models.CharField(max_length=100, db_index=True, verbose_name='Заголовок')
    content = models.TextField(verbose_name='Описание', help_text='Напишите что-то...')
    pub_date = models.DateTimeField(verbose_name='Дата публикации', auto_now_add=True)


class Comment(models.Model):
    name = models.CharField(max_length=20, db_index=True, verbose_name='Название')
    comment = models.CharField(max_length=250, help_text='Напишите короткий коментарий', verbose_name='Коментарий')
    article = models.ForeignKey('Article', on_delete=models.CASCADE, null=True, blank=True,
                                verbose_name='статья')

    class Meta:
        verbose_name = 'Рубрика'
        verbose_name_plural = 'Рубрики'

library/forms.py
from django import forms
from .models import AdvUser
from django.core.exceptions import ValidationError
from django.contrib.auth import password_validation
from .apps import user_register


class ChangeUserInfoForm(forms.ModelForm):
    email = forms.EmailField(required=True, label='Адрес електронной почты')

    class Meta:
        model = AdvUser
        fields = ('username', 'email', 'first_name', 'last_name', 'send_message')


class RegisterUserForm(forms.ModelForm):
    email = forms.EmailField(required=True, label='Адрес електроной почты')
    password1 = forms.CharField(required=True, label='Введите пароль',
                                widget=forms.PasswordInput,
                                help_text=password_validation.password_validators_help_text_html())
    password2 = forms.CharField(required=True, widget=forms.PasswordInput, label='Пароль повторно',
                                help_text='Введите тот же пароль повторно для проверки')

    def clean_password1(self):
        password1 = self.cleaned_data['password1']
        if password1:
            password_validation.validate_password(password1)
        return password1

    def clean(self):
        super().clean()
        password1 = self.cleaned_data['password1']
        password2 = self.cleaned_data['password2']
        if password1 and password2 and password1 != password2:
            errors = {'password2': ValidationError('Введеные пароли несовпадают', code='password_mismatch')}
            raise ValidationError(errors)

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        user.is_active = True
        user.is_activated = False
        if commit:
            user.save()
        #user_register.send(RegisterUserForm, instance=user)
        return user

    class Meta:
        model = AdvUser
        fields = ('username', 'email', 'password1', 'password2', 'first_name', 'last_name', 'send_message')

library/views.py
from django.contrib.auth import logout
from django.shortcuts import render, get_object_or_404
from django.contrib import messages
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.views.generic.edit import UpdateView, CreateView, DeleteView
from django.views.generic.base import TemplateView
from django.views.generic.list import ListView
from .models import AdvUser, Article, Comment
from .forms import ChangeUserInfoForm, RegisterUserForm


def home(request):
    return render(request, 'layout/index.html')


class BookLoginView(LoginView):
    template_name = 'main/login.html'


class BookLogoutView(LoginRequiredMixin, LogoutView):
    template_name = 'main/logout.html'


@login_required
def profile(request):
    return render(request, 'main/profile.html')


class ChangeUserInfoView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = AdvUser
    template_name = 'main/change_info.html'
    form_class = ChangeUserInfoForm
    success_url = reverse_lazy('library:home')
    success_message = 'Данные успешно обновлены'

    def setup(self, request, *args, **kwargs):
        self.user_id = request.user.pk
        return super().setup(request, *args, **kwargs)

    def get_object(self, queryset=None):
        if not queryset:
            queryset = self.get_queryset()
        return get_object_or_404(queryset, pk=self.user_id)


class BookChangePasswordView(PasswordChangeView, LoginRequiredMixin, SuccessMessageMixin):
    template_name = 'main/change_password.html'
    success_url = reverse_lazy('library:home')
    success_message = 'Пароль успешно изменен'


class RegisterUserView(CreateView):
    model = AdvUser
    template_name = 'main/register_user.html'
    form_class = RegisterUserForm
    success_url = reverse_lazy('library:register_done')

    def post(self, request, *args, **kwargs):
        messages.add_message(request, messages.SUCCESS, 'Вы зарегестрировались')
        return super().post(request, *args, **kwargs)


class RegisterDone(TemplateView):
    template_name = 'main/register_done.html'


class BookDeleteView(LoginRequiredMixin, DeleteView):
    model = AdvUser
    template_name = 'main/delete_user.html'
    success_url = reverse_lazy('library:home')

    def setup(self, request, *args, **kwargs):
        self.user_id = request.user.pk
        return super().setup(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        logout(request)
        messages.add_message(request, messages.SUCCESS, 'Пользователь удален')
        return super().post(request, *args, **kwargs)

    def get_object(self, queryset=None):
        if not queryset:
            queryset = self.get_queryset()
        return get_object_or_404(queryset, pk=self.user_id)


# Написать View для написания и сохранения статьей

class CreateArticle(CreateView):
    model = Article
    fields = ['title', 'content']
    success_url = reverse_lazy('library:home')
    template_name = 'main/create_article.html'


def 

library/templates/layout/index.html
{% load bootstrap4 %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"> 
		<meta name="viewport" content="width=device-width, initial-scale=1.0"> 
		<title>{% block title %}Home{% endblock %}</title>
		{% bootstrap_css %}
		<meta name="description" content="A tutorial on how to recreate the effect of YouTube's little left side menu. The idea is to slide a little menu icon to the right side while revealing some menu item list beneath. " />
		<meta name="keywords" content="Add keywords" />
		<meta name="author" content="_yourName_ for Codrops" />
		<link rel="shortcut icon" href="../favicon.ico"> 
		<link rel="stylesheet" type="text/css" href="{% static "css/default.css" %}" />
		<link rel="stylesheet" type="text/css" href="{% static "css/component.css" %}" />
		<script src="{% static "js/modernizr.custom.js" %}"></script>
	</head>
	<body>
		<div class="container">	
			<header class="clearfix">
				<h1>Hello, welcome in my site<span>Rostislav Skomoroha</span></h1>
			</header>
			<div class="main">

				<div class="side">
					<nav class="dr-menu">
						<div class="dr-trigger"><span class="dr-icon dr-icon-menu"></span><a class="dr-label">Account</a></div>
						<ul>
							<li><a class="dr-icon dr-icon-user" href="/">Home</a></li>
							{% if user.is_authenticated %}
							<li><a class="dr-icon dr-icon-user" href="{% url 'library:profile' %}">{{ user.username }}</a></li>
							<li><a class="dr-icon dr-icon-camera" href="{% url 'library:list_article' %}">Статьи</a></li>
							<li><a class="dr-icon dr-icon-heart" href="#">Favorites</a></li>
							<li><a class="dr-icon dr-icon-bullhorn" href="#">Subscriptions</a></li>
							<li><a class="dr-icon dr-icon-download" href="#">Downloads</a></li>
							<li><a class="dr-icon dr-icon-settings" href="{% url 'library:change_info' %}">Change info</a></li>
							<li><a class="dr-icon dr-icon-settings" href="{% url 'library:change_password' %}">Change password</a></li>
							<li><a class="dr-icon dr-icon-user" href="{% url 'library:delete_user' %}">Delete account</a></li>
							<li><a class="dr-icon dr-icon-switch" href="{% url 'library:logout' %}">Logout</a></li>
							{% else %}
							<li><a class="dr-icon dr-icon-user" href="{% url 'library:login' %}">Login</a></li>
							<li><a class="dr-icon dr-icon-user" href="{% url 'library:register_user' %}">Registration</a></li>
							{% endif %}
						</ul>
					</nav>
				</div>
				<div>
					{% block content %}
					<p>This menu is inspired by the left side menu found on YouTube. When clicking on the menu label and icon, the main menu appears beneath and the menu icon slides to the right side while the label slides up. To close the menu, the menu icon needs to be clicked again.</p>
					{% endblock %}
				</div>
			</div>
		</div><!-- /container -->
		<script src="{% static "js/ytmenu.js" %}"></script>

	</body>
</html>

library/templates/main/change_info.html
{% extends 'layout/index.html' %}

{% load bootstrap4 %}

{% block title %}Смена данных{% endblock %}

{% block content %}
<h2>Правка личных данных пользователя: {{ user.username }}</h2>
<form method="post">
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}
    {% buttons submit='Сохранить' %}{% endbuttons %}
</form>
{% endblock %}

library/templates/main/change_password.html
{% extends 'layout/index.html' %}

{% load bootstrap4 %}

{% block title %}Смена пароля{% endblock %}

{% block content %}
<h2>Смена пароля пользователя {{ user.username }}</h2>
<form method="post">
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}
    {% buttons submit='Изменить пароль' %}{% endbuttons %}
</form>
{% endblock %}

library/templates/main/create_article.html
{% extends 'layout/index.html' %}

{% load bootstrap4 %}

{% block title %}Создание новой статьи{% endblock %}

{% block content %}
<h2>Создание новой статьи</h2>
<form method="post">
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}
    {% buttons submit='Создать' %}{% endbuttons %}
</form>
{% endblock %}

library/templates/main/delete_user.html
{% extends 'layout/index.html' %}

{% load bootstrap4 %}

{% block title %}Удаление пользователя{% endblock %}

{% block content %}
<h2>Удаление пользователя</h2>
<form method="post">
    {% csrf_token %}
    {% buttons submit='Удалить' %}{% endbuttons %}
</form>
{% endblock %}

library/templates/main/login.html
{% extends 'layout/index.html' %}

{% load bootstrap4 %}

{% block title %}Вход{% endblock %}

{% block content %}
    <h2>Вход</h2>
    {% if user.is_authenticated %}
    <p>Вы уже выполнили вход</p>
    {% else %}
    <form method="post">
        {% csrf_token %}
        {% bootstrap_form form layout='horizontal' %}
        <input type="hidden" name="next" value="{{ next }}">
        {% buttons submit='Войти' %}{% endbuttons %}
    </form>
{% endif %}
{% endblock %}

library/templates/main/logout.html
{% extends 'layout/index.html' %}

{% block title %}Выход{% endblock %}

{% block content %}
    <h2>Вы успешно вышли с аккаунта</h2>
    <p>Заходите к нам ещё</p>
{% endblock %}

library/templates/main/profile.html
{% extends 'layout/index.html' %}

{% block title %}Профиль пользователя{% endblock %}

{% block content %}
    <h2>Профиль пользователя: {{ user.username }}</h2>
    {% if user.first_name and user.last_name %}
    <p>Здраствуйте, {{ user.first_name }} {{ user.last_name }}</p>
    {% else %}
    <p>Здраствуйте!</p>
    {% endif %}
    <p>Ваши избранные книги</p>
    <a href="{% url 'library:create_article' %}">Создать статью</a>
{% endblock %}

library/templates/main/register_done.html
{% extends 'layout/index.html' %}

{% load bootstrap4 %}

{% block title %}Регистрация прошла успешно{% endblock %}

{% block content %}
<h2>Регистрация пользователя прошла успешно</h2>
<p>Перейдите по ссылке в письме, которое мы отправили Вам на почту для подтверджения регистрации</p>
<p>Спасибо!)</p>
{% endblock %}

library/templates/main/register_user.html
{% extends 'layout/index.html' %}

{% load bootstrap4 %}

{% block title %}Регистрация{% endblock %}

{% block content %}
<h2>Регистрация пользователя</h2>
<form method="post">
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}
    {% buttons submit='Зарегестрироватся' %}{% endbuttons %}
</form>
{% endblock %}